### ISSUE TITLE
ImagenetV2 dataset issue

### ISSUE THREAD

**Issue by szubing** [linzhiqiu/cross_modal_adaptation#1]
Thanks for the very nice code. Is looks like the imagenetV2 dataset is not available to download at https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz

Is there any other path to download that?

**Comment by linzhiqiu** [comment]
It seems ImageNetV2 is recently moved to HuggingFace: https://github.com/modestyachts/ImageNetV2/issues/12

I have updated the download link. You can use wget to download from: https://huggingface.co/datasets/vaishaal/ImageNetV2/blob/main/imagenetv2-matched-frequency.tar.gz

**Comment by szubing** [comment]
> It seems ImageNetV2 is recently moved to HuggingFace: [modestyachts/ImageNetV2#12](https://github.com/modestyachts/ImageNetV2/issues/12)
> 
> I have updated the download link. You can use wget to download from: https://huggingface.co/datasets/vaishaal/ImageNetV2/blob/main/imagenetv2-matched-frequency.tar.gz

Thanks very much. You are really nice _^_
