### ISSUE TITLE
关于复现精度的问题

### ISSUE THREAD

**Issue by ZY123-GOOD** [linzhiqiu/cross_modal_adaptation#10]
您好，这篇论文和代码清晰明了，感谢您的分享。

**Comment by ZY123-GOOD** [comment]
{'val_acc': 0.64575, 'iter': 2500, 'test_accs': {'head': 0.63588, 'head_wiseft_0.5': 0.64476}}

**Comment by linzhiqiu** [comment]
Thank you for the kind words!
