### ISSUE TITLE
About image encoder.

### ISSUE THREAD

**Issue by HlEvag** [linzhiqiu/cross_modal_adaptation#12]
A very good job!
Since my image data has a very large number of bands, I have to use my own image encoder. The text encoder still comes with clip. But the results were so-so. Why? Any good suggestions? 
Thank you very much!

**Comment by linzhiqiu** [comment]
Could you provide details on the image encoder you used? 

For this method to work, we need a cross-modal representation space where the two modalities are aligned during pre-training. I wouldn't expect it to work with two unrelated image and text encoder.

**Comment by HlEvag** [comment]
Thank you for your reply！
For my own research, I used remote sensing image which was decomposed into patch-based data input network, that is to say, the size of my image was W*W*D, where W and D were 9 and 100 respectively, so I could not use the image encoder in clip. Therefore, my thoughts include the following two aspects:
(1) Build your own image encoder, which is built based on CNN.
(2) As you thought, I used clip's text encoder to train a better visual encoder. In the training process, the image encoder built by myself needs to be trained, but the text encoder in clip is frozen .
Is my idea reasonable and achievable? Look forward to your reply, thank you!


| |
hulei9608
|
|
15156565431
***@***.***
武汉大学 测绘遥感信息工程国家重点实验室
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/21/2023 04:55 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [linzhiqiu/cross_modal_adaptation] About image encoder. (Issue #12) |

Could you provide details on the image encoder you used?

For this method to work, we need a cross-modal representation space where the two modalities are aligned during pre-training. I wouldn't expect it to work with two unrelated image and text encoder.

**Comment by linzhiqiu** [comment]
I'm not sure if my codebase is what you need if your goal is train a better visual representation for remote sensing images. You might want to train a CLIP from scratch using their codebase?

**Comment by HlEvag** [comment]
Thank you for your reply!

The more I read your article, the more interesting and exciting it is! However, I still have some questions:

1. For the cross-modal adaptive method you proposed, which maps images and texts to the same dimension and then combines them to train the classifier, do I understand it correctly? Whether the cross-modal adaptive approach here is plug and play or not. 2. From your pseudo-code, you fine-tuned the image encoder and text encoder in the clip model, right? Not just training the classification head 'LogitHead'.
 3. Does your template  mining strategy have a corresponding code address, can I learn it?
Looking forward to your reply. Thank you!
| |
hulei9608
|
|
15156565431
***@***.***
武汉大学 测绘遥感信息工程国家重点实验室
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/21/2023 11:41 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [linzhiqiu/cross_modal_adaptation] About image encoder. (Issue #12) |

I'm not sure if my codebase is what you need if your goal is train a better visual representation for remote sensing images. You might want to train a CLIP from scratch using their codebase?

**Comment by linzhiqiu** [comment]
1. Our approach relies on CLIP or AudioCLIP that are pretrained to map different modalities into the same dimensional space.

2. You can indeed finetune the visual encoder of CLIP when you have more data.

3. If you are referring to the repo, we simply copied them from CoOp/Tip-Adapter codebase for fair comparison. In practice you can change them in whatever ways you want to maximize performance.
