### ISSUE TITLE
Could not download StanfordCars?

### ISSUE THREAD

**Issue by baiyuting** [linzhiqiu/cross_modal_adaptation#14]
Following [DATASETS.md](https://github.com/linzhiqiu/cross_modal_adaptation/blob/main/DATASETS.md),  I could not download StanfordCars, could you update the download link given for downloading StanfordCars?

**Comment by linzhiqiu** [comment]
Please use this link first: https://drive.google.com/file/d/1mg_uaJ0WoMO7hLapkPNrsFOkpjZaA5lq/view?usp=sharing

**Comment by linzhiqiu** [comment]
Please use this link now: https://drive.google.com/file/d/150nwNkg7qXh28yabiqNAOfBMMll7ALlu/view?usp=drive_link
