### ISSUE TITLE
Where is the path to the“ text_encoder” defined 

### ISSUE THREAD

**Issue by jesi688** [linzhiqiu/cross_modal_adaptation#15]
When running domain_shift.py, I get the following error:
Traceback (most recent call last):
  File "\cross_modal_adaptation-main\domain_shift.py", line 425, in <module>
    main(args)
  File "\cross_modal_adaptation-main\domain_shift.py", line 215, in main
    head, num_classes, in_features = make_classifier_head(
TypeError: make_classifier_head() missing 1 required positional argument: 'text_encoder'
I want you to tell me the exact location of the text_encoder path so that I can modify the path to avoid the error

**Comment by linzhiqiu** [comment]
Thank you for spotting this bug. I updated the domain_shift.py file that hopefully fixes this issue (sorry I didn't have time to test).

If you want to fix it yourself, you just need to move up the line of code that loads the text_encoder, which was right below.

```
image_encoder = torch.load(
                        image_encoder_path).partial_model.train().cuda()
text_encoder = torch.load(
                        text_encoder_path).partial_model.train().cuda()
head, num_classes, in_features = make_classifier_head(
                        args.classifier_head,
                        args.clip_encoder,
                        args.classifier_init,
                        text_dataset,
                        text_encoder
                    )
                    ```

**Comment by jesi688** [comment]
Thank you for your reply. After your tips, I realized that this error might be caused by the missing keyword, change the code to the following, it can run successfully
#zero_shot_weights = get_zero_shot_weights(text_dataset, num_classes, in_features)
**zero_shot_weights = get_zero_shot_weights(text_dataset, num_classes, in_features,text_encoder)**

**Comment by jesi688** [comment]
> Owner  
Thank you for your reply. After your tips, I realized that this error might be caused by the missing keyword, change the code to the following, it can run successfully
#zero_shot_weights = get_zero_shot_weights(text_dataset, num_classes, in_features)
**zero_shot_weights = get_zero_shot_weights(text_dataset, num_classes, in_features,text_encoder)**
