### ISSUE TITLE
关于重复进行encode的问题

### ISSUE THREAD

**Issue by daijiuqian** [linzhiqiu/cross_modal_adaptation#18]
您好，我仔细看了您的代码。我发现您在feature.py文件中，对于image和text进行了extract feature，并保存到为文件。但是在train文件中，您将这些feature做成了tensor dataset。然后，这些tensor dataset制作得到的loader送到了train函数中，在train函数中，您又使用image encoder和text encoder对这些feature进行了encode的操作，然后进行了梯度更新。这样不就是对于image数据进行了两次的encode吗？
不知道我对代码的解读对不对，如果确实是这样的操作，请问为什么要这么做呢？

**Comment by linzhiqiu** [comment]
为了节省训练时间，我们代码会将CLIP image encoder分成两个部分。feature.py会用image encoder的第一个部分提取特征，而train.py会用image encoder的第二个部分进行训练。这个过程不存在重复encoding。具体而言：

对于linear probing来说，image encoder的第一个部分就是全部的encoder，第二个部分是nn.Identity()。
对于partial finetuning来说，image encoder的第一个部分是除了最后一层layer之外的所有layers，第二个部分是最后一层layer （ResNet是attention pooling layer，ViT是最后一个Transformer block）。
