### ISSUE TITLE
where is the  L2 normalize?

### ISSUE THREAD

**Issue by SHIBOYA** [linzhiqiu/cross_modal_adaptation#2]
in Algorithm 1, you claim "Concatenate then L2 normalize",  can't find this in your code？

**Comment by linzhiqiu** [comment]
Concatenation simply means put both image and text features into a batch: https://github.com/linzhiqiu/cross_modal_adaptation/blob/eda150f02a821191419e84e4d594039009d0ade7/train.py#L186

L2-normalization is done in logit_head (a wrapper for linear classifier that does L2-norm and temperature scaling): https://github.com/linzhiqiu/cross_modal_adaptation/blob/eda150f02a821191419e84e4d594039009d0ade7/engine/model/logit.py#L18
