### ISSUE TITLE
Where do the results cited in the paper comparing to SOTA methods come from?

### ISSUE THREAD

**Issue by ZhenweiWan** [linzhiqiu/cross_modal_adaptation#8]
I read your paper carefully. When citing other methods for performance comparison (Table 1 and Table 10 in the original paper), I did not find the results of the other methods you cited in the original paper, such as CoOp. As a result, I only found in the original paper of CoOp that they gave a line graph on 11 datasets and a line graph of the average results of these 11 datasets. Can you tell me how you got these specific values? Thank you so much.

**Comment by linzhiqiu** [comment]
@samuelyu2002 either found the results from their paper or repo, or ran their code. Let us know if you run into issues when reproducing the results.
